<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Company;
use App\Models\Product;
use App\Models\Unit;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $allergy     = Category::where('name', 'Allergy')->first();
        $antibiotics = Category::where('name', 'Antibiotics')->first();
        $vitamins    = Category::where('name', 'Vitamins')->first();
        $painkillers = Category::where('name', 'Painkillers')->first();
        $digestive   = Category::where('name', 'Digestive')->first();
        $dermatology = Category::where('name', 'Dermatology')->first();
        $cardio      = Category::where('name', 'Cardiovascular')->first();
        $diabetes    = Category::where('name', 'Diabetes')->first();
        $others      = Category::where('name', 'Others')->first();

        $box     = Unit::where('name', 'Box')->first();
        $tablet  = Unit::where('name', 'Tablet')->first();
        $capsule = Unit::where('name', 'Capsule')->first();
        $bottle  = Unit::where('name', 'Bottle')->first();
        $gram    = Unit::where('name', 'Gram')->first();

        $syr      = Company::where('name', 'Syrian Pharma')->first();
        $cham     = Company::where('name', 'Cham Pharma')->first();
        $sama     = Company::where('name', 'Sama Pharma')->first();
        $hama     = Company::where('name', 'Hama Pharma')->first();
        $averroes = Company::where('name', 'Averroes Pharma')->first();
        $uni      = Company::where('name', 'Unipharma')->first();
        $barakat  = Company::where('name', 'Barakat Pharma')->first();

        $now = Carbon::now();

        $products = [
            // ── Core products (keep original barcodes) ─────────────────────────
            [
                'pharmacy_id'           => 1,
                'category_id'           => $allergy->id,
                'company_id'            => $syr?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066555',
                'brand_name'            => 'Panadol Extra',
                'ar_name'               => 'بانادول إكسترا',
                'scientific_name'       => 'Paracetamol / Caffeine',
                'strength'              => '500mg/65mg',
                'prescription_required' => false,
                'buying_price'          => 4500.00,
                'selling_price'         => 5500.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 10,
                'units_per_base'        => 20,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
            [
                'pharmacy_id'           => 1,
                'category_id'           => $antibiotics->id,
                'company_id'            => $syr?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $capsule?->id,
                'barcode'               => '6211269066556',
                'brand_name'            => 'Amoxil 500mg',
                'ar_name'               => 'أموكسيل 500 مغ',
                'scientific_name'       => 'Amoxicillin',
                'strength'              => '500mg',
                'prescription_required' => true,
                'buying_price'          => 12000.00,
                'selling_price'         => 15000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 5,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
            [
                'pharmacy_id'           => 1,
                'category_id'           => $vitamins->id,
                'company_id'            => $cham?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066557',
                'brand_name'            => 'Centrum Lutein',
                'ar_name'               => 'سنتروم لوتين',
                'scientific_name'       => 'Multivitamins / Minerals',
                'strength'              => null,
                'prescription_required' => false,
                'buying_price'          => 85000.00,
                'selling_price'         => 95000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 3,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
            [
                'pharmacy_id'           => 1,
                'category_id'           => $painkillers->id,
                'company_id'            => $sama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066558',
                'brand_name'            => 'Concor 5mg',
                'ar_name'               => 'كونكور 5 مغ',
                'scientific_name'       => 'Bisoprolol',
                'strength'              => '5mg',
                'prescription_required' => true,
                'buying_price'          => 18000.00,
                'selling_price'         => 22000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 15,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
            [
                'pharmacy_id'           => 1,
                'category_id'           => $antibiotics->id,
                'company_id'            => $sama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066559',
                'brand_name'            => 'Augmentin 1g',
                'ar_name'               => 'أوغمنتين 1 غ',
                'scientific_name'       => 'Amoxicillin / Clavulanate Potassium',
                'strength'              => '1g',
                'prescription_required' => true,
                'buying_price'          => 45000.00,
                'selling_price'         => 52000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 8,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // ── Additional products for richer reports ─────────────────────────

            // Digestive — high margin, sells well → Top Products & Profit variety
            [
                'pharmacy_id'           => 1,
                'category_id'           => $digestive?->id ?? $antibiotics->id,
                'company_id'            => $cham?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $capsule?->id,
                'barcode'               => '6211269066560',
                'brand_name'            => 'Omeprazole 20mg',
                'ar_name'               => 'أوميبرازول 20 مغ',
                'scientific_name'       => 'Omeprazole',
                'strength'              => '20mg',
                'prescription_required' => false,
                'buying_price'          => 8000.00,
                'selling_price'         => 13000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 10,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // Dermatology — medium margin, moderate sales
            [
                'pharmacy_id'           => 1,
                'category_id'           => $dermatology?->id ?? $vitamins->id,
                'company_id'            => $syr?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066561',
                'brand_name'            => 'Betadine 500ml',
                'ar_name'               => 'بيتادين 500 مل',
                'scientific_name'       => 'Povidone-Iodine',
                'strength'              => '10%',
                'prescription_required' => false,
                'buying_price'          => 22000.00,
                'selling_price'         => 30000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 5,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // Cardiovascular — expensive, low sales → will become near-dead stock
            [
                'pharmacy_id'           => 1,
                'category_id'           => $cardio?->id ?? $painkillers->id,
                'company_id'            => $sama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066562',
                'brand_name'            => 'Crestor 10mg',
                'ar_name'               => 'كريستور 10 مغ',
                'scientific_name'       => 'Rosuvastatin',
                'strength'              => '10mg',
                'prescription_required' => true,
                'buying_price'          => 65000.00,
                'selling_price'         => 78000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 5,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // Diabetes — low stock scenario (min_stock=10, will seed only 2 units)
            [
                'pharmacy_id'           => 1,
                'category_id'           => $diabetes?->id ?? $antibiotics->id,
                'company_id'            => $cham?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211269066563',
                'brand_name'            => 'Glucophage 1000mg',
                'ar_name'               => 'غلوكوفاج 1000 مغ',
                'scientific_name'       => 'Metformin',
                'strength'              => '1000mg',
                'prescription_required' => true,
                'buying_price'          => 15000.00,
                'selling_price'         => 20000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 10,   // high threshold → will show as low-stock
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // ═════════════════════════════════════════════════════════════════
            // Additional real-world products (imported dataset) — barcodes 19-31
            // ═════════════════════════════════════════════════════════════════

            // 19 — Anti-Tussive Hama Pharma (cough syrup) — regular seller + supplier history
            [
                'pharmacy_id'           => 1,
                'category_id'           => $others?->id ?? $digestive->id,
                'company_id'            => $hama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $bottle?->id,
                'barcode'               => '6215267055890',
                'brand_name'            => 'Anti-Tussive Hama Pharma',
                'ar_name'               => 'أنتي توسيف حماة فارما',
                'scientific_name'       => 'Paracetamol / Guaifenesin / Sodium Benzoate / Oxomemazine',
                'strength'              => '33.3mg/33.3mg/33.3mg/1.65mg per 5ml',
                'prescription_required' => false,
                'buying_price'          => 6500.00,
                'selling_price'         => 9000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 8,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 20 — Unadol FORTE (Paracetamol 1000mg) — fresh, near-expiry variant later
            [
                'pharmacy_id'           => 1,
                'category_id'           => $painkillers->id,
                'company_id'            => $hama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6212235151837',
                'brand_name'            => 'Unadol FORTE',
                'ar_name'               => 'يونادول فورت',
                'scientific_name'       => 'Paracetamol',
                'strength'              => '1000mg',
                'prescription_required' => false,
                'buying_price'          => 3500.00,
                'selling_price'         => 5000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 15,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 21 — SPASMAVER (Alverine Citrate) — dead stock candidate
            [
                'pharmacy_id'           => 1,
                'category_id'           => $digestive?->id ?? $painkillers->id,
                'company_id'            => $averroes?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211960110102',
                'brand_name'            => 'Spasmaver',
                'ar_name'               => 'سبازمافير',
                'scientific_name'       => 'Alverine Citrate',
                'strength'              => '40mg',
                'prescription_required' => false,
                'buying_price'          => 9000.00,
                'selling_price'         => 12500.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 5,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 22 — UNI BRUFEN 400mg (Ibuprofen) — high-volume regular seller
            [
                'pharmacy_id'           => 1,
                'category_id'           => $painkillers->id,
                'company_id'            => $uni?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6212236301859',
                'brand_name'            => 'Uni Brufen 400mg',
                'ar_name'               => 'يوني بروفين 400 مغ',
                'scientific_name'       => 'Ibuprofen',
                'strength'              => '400mg',
                'prescription_required' => false,
                'buying_price'          => 5000.00,
                'selling_price'         => 7000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 20,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 23 — BRANDEX-P ointment (Silver Sulphadiazine / Panthenol) — low-stock scenario
            [
                'pharmacy_id'           => 1,
                'category_id'           => $dermatology?->id ?? $vitamins->id,
                'company_id'            => $uni?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $gram?->id,
                'barcode'               => '6211369085360',
                'brand_name'            => 'Brandex-P',
                'ar_name'               => 'براندكس بي',
                'scientific_name'       => 'Silver Sulphadiazine / Panthenol',
                'strength'              => '10mg+50mg per 1g',
                'prescription_required' => false,
                'buying_price'          => 11000.00,
                'selling_price'         => 15500.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 10,   // will be seeded low → low-stock scenario
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 24 — LOSARTIC (Losartan / HCTZ) — regular seller + supplier history
            [
                'pharmacy_id'           => 1,
                'category_id'           => $cardio?->id ?? $painkillers->id,
                'company_id'            => $barakat?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6211908012079',
                'brand_name'            => 'Losartic',
                'ar_name'               => 'لوسارتيك',
                'scientific_name'       => 'Losartan Potassium / Hydrochlorothiazide',
                'strength'              => '50mg/12.5mg',
                'prescription_required' => true,
                'buying_price'          => 16000.00,
                'selling_price'         => 21000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 12,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 25 — PANTHENOL RAMA (Dexpanthenol cream) — near-expiry scenario
            [
                'pharmacy_id'           => 1,
                'category_id'           => $dermatology?->id ?? $vitamins->id,
                'company_id'            => $barakat?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $gram?->id,
                'barcode'               => '6214376085354',
                'brand_name'            => 'Panthenol Rama',
                'ar_name'               => 'بانثينول راما',
                'scientific_name'       => 'Dexpanthenol',
                'strength'              => '5% (5g per 100g)',
                'prescription_required' => false,
                'buying_price'          => 4500.00,
                'selling_price'         => 6500.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 8,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 26 — FUCINE Dermic Ointment (Sodium Fusidate) — regular seller
            [
                'pharmacy_id'           => 1,
                'category_id'           => $dermatology?->id ?? $vitamins->id,
                'company_id'            => $averroes?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $gram?->id,
                'barcode'               => '6211269066551',
                'brand_name'            => 'Fucine Dermic Ointment',
                'ar_name'               => 'فيوسين مرهم جلدي',
                'scientific_name'       => 'Sodium Fusidate',
                'strength'              => '20mg per 1g',
                'prescription_required' => true,
                'buying_price'          => 9500.00,
                'selling_price'         => 13500.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 6,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 27 — TOULARYNX THYM (Thymus vulgaris extract syrup) — critical near-expiry
            [
                'pharmacy_id'           => 1,
                'category_id'           => $others?->id ?? $digestive->id,
                'company_id'            => $hama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $bottle?->id,
                'barcode'               => '6211043321819',
                'brand_name'            => 'Toularynx Thym',
                'ar_name'               => 'تولارينكس ثيم',
                'scientific_name'       => 'Thymus vulgaris extract',
                'strength'              => '5g per 100g',
                'prescription_required' => false,
                'buying_price'          => 4000.00,
                'selling_price'         => 6000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 6,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 28 — New Bonacare (multivitamin/mineral) — regular seller
            [
                'pharmacy_id'           => 1,
                'category_id'           => $vitamins->id,
                'company_id'            => $sama?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6214157090140',
                'brand_name'            => 'New Bonacare',
                'ar_name'               => 'نيو بوناكير',
                'scientific_name'       => 'Calcium / Magnesium / Vitamin D3 / Manganese / Copper / Boron / Zinc',
                'strength'              => '600mg Calcium per tablet',
                'prescription_required' => false,
                'buying_price'          => 14000.00,
                'selling_price'         => 19000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 8,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 29 — OSTEODAM PLUS K2 — supplier price history variety
            [
                'pharmacy_id'           => 1,
                'category_id'           => $vitamins->id,
                'company_id'            => $cham?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '8682005327584',
                'brand_name'            => 'Osteodam Plus K2',
                'ar_name'               => 'أوستيودام بلس K2',
                'scientific_name'       => 'Calcium / Vitamin D3 / Vitamin K2 / Zinc / Magnesium / Copper / Manganese / Boron',
                'strength'              => '400mg Calcium',
                'prescription_required' => false,
                'buying_price'          => 17000.00,
                'selling_price'         => 23000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 8,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 30 — NoFlu DAY And NIGHT — seasonal (cold) seller
            [
                'pharmacy_id'           => 1,
                'category_id'           => $others?->id ?? $painkillers->id,
                'company_id'            => $syr?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $tablet?->id,
                'barcode'               => '6216367020146',
                'brand_name'            => 'NoFlu Day And Night',
                'ar_name'               => 'نوفلو نهار وليل',
                'scientific_name'       => 'Paracetamol / Phenylephrine HCl / Dextromethorphan HBr / Chlorpheniramine Maleate',
                'strength'              => '500mg/5mg/15mg (+2mg night)',
                'prescription_required' => false,
                'buying_price'          => 7500.00,
                'selling_price'         => 10500.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 10,
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],

            // 31 — One-Asian 1 (Alfacalcidol) — critical low-stock
            [
                'pharmacy_id'           => 1,
                'category_id'           => $vitamins->id,
                'company_id'            => $barakat?->id,
                'base_unit_id'          => $box?->id,
                'selling_unit_id'       => $capsule?->id,
                'barcode'               => '6211121087465',
                'brand_name'            => 'One-Asian 1',
                'ar_name'               => 'ون آسيان 1',
                'scientific_name'       => 'Alfacalcidol',
                'strength'              => '1mcg',
                'prescription_required' => true,
                'buying_price'          => 13000.00,
                'selling_price'         => 18000.00,
                'tax_rate'              => 0.00,
                'discount_rate'         => 0.00,
                'min_stock'             => 10,   // will be seeded low → low-stock scenario
                'units_per_base'        => 1,
                'allow_partial_selling' => false,
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
        ];

        Product::insert($products);
    }
}
